# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main # Change this to your default branch if different

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Install Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Build the project
#         run: npm run build

#       - name: Deploy to GitHub Pages
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#         run: |
#           git config --global user.email "pavelsh00@gmail.com"
#           git config --global user.name "pavelshm10"
#           npm install -g gh-pages
#           git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/pavelshm10/nestjs.git
#           npm run deploy
      
#       # - name: Configure AWS credentials
#       #   uses: aws-actions/configure-aws-credentials@v1
#       #   with:
#       #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       #     aws-region: us-east-1

#       # - name: Deploy to AWS Amplify
#       #   run: |
#       #     npm install -g @aws-amplify/cli
#       #     amplify init --yes
#       #     amplify publish --yes


name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your main branch name
  # You can add more triggers as needed, such as pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Or use `yarn install` if you prefer Yarn

      - name: Build
        run: CI=false npm run build  # Or `yarn build` for Yarn

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "pavelsh00@gmail.com"
          git config --global user.name "pavelshm10"
          git checkout --orphan gh-pages
          git --work-tree build add --all
          git --work-tree build commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force
