name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "pavelsh00@gmail.com"
          git config --global user.name "pavelshm10"
          npm run deploy  # Adjust if your deployment script/command differs

      - name: Cleanup
        run: rm -rf node_modules  # Clean up node_modules to reduce repo size
